### ISSUE TITLE
Any luck with multitouch scrolling?

### ISSUE THREAD

**Issue by ianks** [nuclearsandwich/surface3-archlinux#19]
Does anyone have any info on getting the touchscreen to recognize multitouch? I am able to get all of the events by running:

`sudo evtest /dev/input/event15`

The device is registed as 'NTRG0001:01 1B96:1B05' in xinputs, but it doesnt seem to have any synaptic capabilities registed with it. Does this mean I cannot use multitouch features?

**Comment by nuclearsandwich** [comment]
@ianks I dunno how I missed this issue. But I think your question in the other thread should've resolved this. Any other problems? Sorry I missed it initially.

**Comment by ianks** [comment]
Sorry I forgot this was still open :smile:
