### ISSUE TITLE
Surface 3 cover (not pro) doesn't work.

### ISSUE THREAD

**Issue by james-lawrence** [nuclearsandwich/surface3-archlinux#23]
[bug reference](https://bugzilla.kernel.org/show_bug.cgi?id=97951)
[patch is available](http://www.spinics.net/lists/linux-input/msg40022.html)
[seems slated to be released in 4.3](http://www.spinics.net/lists/linux-input/msg40077.html)

**Comment by james-lawrence** [comment]
@staticfloat (in case you are interested in tracking it)

**Comment by staticfloat** [comment]
Thank you James, I am definitely interested.  When you say "4.3", are you referring to the kernel version?  Is there an easy way I can figure out what timeframe that corresponds to?

**Comment by james-lawrence** [comment]
yes kernel version. its definitely in [master](https://github.com/torvalds/linux/commit/0439de75d32c249bd9f5824ffd5e40c4c2109d77) and looks like it first appears in [v4.3-rc1](https://github.com/torvalds/linux/releases/tag/v4.3-rc1) which was tagged 2 days ago.

**Comment by james-lawrence** [comment]
4.2 landed in core repository today, I expect 4.3 to land in testing in a few days hopefully.

**Comment by james-lawrence** [comment]
got tired of waiting, prepackaged [kernel 4.3-rc6.](https://drive.google.com/file/d/0B4tQhII1sO_JLXlhNnhOQUtZaGM/view?usp=sharing) it did fix the issue with the type cover.

**Comment by james-lawrence** [comment]
4.3 landed in testing the other day. closing issue.
